### ISSUE TITLE
Ensure that entity fields in mappings match up with GraphQL schema types

### ISSUE THREAD

**Issue by nenadjaja** [graphprotocol/graph-tooling#126]
Right now, when creating mappings, you can set pretty much anything on your entities, for example:
`auction.setString('test', event.params.test)` even though `test` is not a field on the entity `Auction`. As a consequence, the database schema that gets created could be messed up. 

Potential solution would be to introduce some restrictions, in form of error messages or warnings for when that happens.

**Comment by Jannis** [comment]
We're going to improve this through AssemblyScript types generated from the GraphQL schema. Instead of
```js
let meme = new Entity();
meme.setString('caption', 'LOL')
meme.setString('invalidField', 'b0rk')
```
developers can then do:
```js
let meme = new Meme()
meme.caption = 'LOL'
meme.invalidField = 'b0rk' // Will fail to build
```

We're also considering to allow `new Meme(memeData: MemeData)`
```js
let meme = new Meme({
  caption: 'LOL',
  invalidField: 'b0rk',
})
```
if AssemblyScript supports optional fields on structs. Depending on the AssemblyScript compiler behavior, passing in `invalidField` would either fail to build or silently be ignored. To support this type of entity construction, AssemblyScript needs to support optional struct fields (`MemeData` must not require all fields to be set; so we can apply partial updates).

Note: There are additional ways to check this at runtime but the above would already takes a long way.
