### ISSUE TITLE
zkSync API fetching is broken

### ISSUE THREAD

**Issue by saihaj** [graphprotocol/graph-tooling#1374]
ZkSync explorer is not the same api to grab ABI compared to etherscan like explorers

context:
![CleanShot 2023-06-13 at 16 07 12@2x](https://github.com/graphprotocol/graph-tooling/assets/44710980/0dd6bcb7-d236-463a-8361-8ee9fbeb6a99)

**Comment by saihaj** [comment]
waiting for ZkSync team to expose API so we can download ABI

**Comment by uF4No** [comment]
@saihaj The zkSync Explorer API is Etherscan compatible since July 2023 (more [info in our docs](https://docs.zksync.io/build/tooling/block-explorer/block-explorer-api.html) and it was integrated in the graph cli tool [in this PR](https://github.com/graphprotocol/graph-tooling/pull/1410) so I think we can close this issue.
