### ISSUE TITLE
validate that mappings only set valid fields

### ISSUE THREAD

**Issue by azf20** [graphprotocol/graph-tooling#1455]
Previously using `store.set` you could set non-existent fields on an entity. This is a determinism bug (depending on whether the entity is fetched from the cache or the store). This was fixed in https://github.com/graphprotocol/graph-node/pull/4807. We should ideally catch this behaviour at build time, rather than failing at runtime.

**Comment by saihaj** [comment]
after some more thought and discussions internally. This is great idea, there are few ways we could go about and none of them are reasonable as of now:

1. At AssmeblyScript level if generic types were possible [similar to how in TypeScript ](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYg9nKBvAUFdUCWATAXAZ2ACdMA7AcwBo0NSBDAWwlykJIuoyjvOalICuDAEYQiKAL4oUAYzilC3FvEQBeZDXQ5cAIgCMOzrUbMdAK3mHN3XiwBMevZOkAzAaRnBM81hGAAeAFFSL1AAPgAKCBDMUBZg0JBKKAA3OgAbAT4AawgQOBcoBNiQKABKZCkUfD8IumSdHB0y6tr6nRk6ImagA) we can write some generics and let structural typings and rely on TS complier. But sadly we can't use the Typescript generics example I shared in AssemblyScript. 
2. We can try to do this validation at a pre-build step. Which is computationally expensive and we will end up building our custom type checker which is much more involved project and not sure how much benefit there is given this is a rare case we are helping avoid developers
3. AssemblyScript doesn't have `protected` or `private` class members, that would have been simplest way where we force users to always use Entities and set values on the field instead of being able to call arbitrary `.set()` on an entity which could avoid lot of these issues.


Maybe if this becomes too big of an issue we should considerer re-opening and maybe by then there are some improvements in AssmeblyScript that we can build on top of.
