### ISSUE TITLE
I can't install graph-cli v0.18.0

### ISSUE THREAD

**Issue by xeious** [graphprotocol/graph-tooling#1460]
I'm trying to install the version 0.18.0 of graph-cli because I'm dealing with Compound-v2 graph and it's not working because the pkg `concat-stream@github:hugomrdias/concat-stream#feat/smaller` isn't maintained anymore although it's not listed in npm dependencies.

**Comment by saihaj** [comment]
hey @xeious we have dropped support for this version, since it no longer support the current node LTS.

I would recommend you upgrading this version so you are on the latest version of CLI. 

But for some reason you need an old API version because of subgraph `apiVersion` you can try these versions https://github.com/graphprotocol/graph-tooling/issues/1414#issuecomment-1675545669
