### ISSUE TITLE
allow passing `spkg.io` from `graph init`

### ISSUE THREAD

**Issue by saihaj** [graphprotocol/graph-tooling#1641]
Pull the substream package from `spkg.io` 

![image](https://github.com/graphprotocol/graph-tooling/assets/44710980/94aebd7b-279f-412d-8f21-a4a45965074c)

**Comment by joshuanazareth97** [comment]
@saihaj can I pick this to work on next?

**Comment by saihaj** [comment]
go for it @joshuanazareth97

**Comment by joshuanazareth97** [comment]
@saihaj Notes on my understanding / the implementation I am planning:

- As I understand it, there are 2 locations from which we could receive spkgPath: (1) flag (2) interactive prompt
- The value received from either of these is passed into the same `initSubgraphFromContract` method, which then adds this to the manifest file under `source`
- Currently, the file must exist in the path relative to the directory that `graph init` is called in

Approach:
- Change the validation for the spkg file to also pass for the URL format above (spkg.io.../.../)
- If we receive a URL, download the file into the current directory
- In this case spkgPath becomes the name of the spkg file, since it is in the root of the current directory
- Continue as before, passing spkgPath into the manifest, just like with local files

Bonus:
- Potential UX improvement: If a URL is passed, we can further ask the user which directory they want to download the spkg file into, defaulting to the current dir. This would give more control to the user, but would require additional logic for creating non-existent folders etc.

Interested to know your thoughts around this approach.

**Comment by joshuanazareth97** [comment]
Hey @saihaj, have implemented this using a slight variation of the approach above. have not yet implemented the bonus feature I mentioned, do let me know if there's anything you'd like me to change?

**Comment by YaroShkvorets** [comment]
implemented in 0.93
