### ISSUE TITLE
Network list during `graph init` is not scrollable, only searchable. (Maybe this is a feature and not a bug)

### ISSUE THREAD

**Issue by schmidsi** [graphprotocol/graph-tooling#1853]
See:

<img width="847" alt="Screenshot 2024-12-18 at 14 43 37" src="https://github.com/user-attachments/assets/1b47db40-b019-4b96-a12e-c0bcf496dff7" />

I think it would be cool if I can
- Scroll through all chains just with the arrow keys
- It would take the whole terminal size to display chains
- Chains are sorted alphabetically

**Comment by YaroShkvorets** [comment]
Scrolling AND searching is tough with this terminal UI library we are using. Let me take another stab at it, see what we can do.

Right now chains with indexing rewards are on top. I feel like these will be the most used ones, makes sense to have them there. Otherwise we end up with some obscure ones and some testnets near the top.

In general, I feel like when somebody wants to build a subgraph they already know what chain to look for, so scrolling through 100+ options seems unnecessary, no?

**Comment by schmidsi** [comment]
> In general, I feel like when somebody wants to build a subgraph they already know what chain to look for, so scrolling through 100+ options seems unnecessary, no?

Right. I agree. Maybe I just missed the old UI but the new flow generally makes more sense with 100+ chains.
