### ISSUE TITLE
Hang on yarn step during graph init.

### ISSUE THREAD

**Issue by jMyles** [graphprotocol/graph-tooling#327]
At EthBerlinZwei, had a hang on `Install dependencies with yarn` - passing `--debug` produced no additional output.

```
jmyles@lurkambo ~/projects/graph-node $ graph init --from-example jMyles/cypherbabies-sandbox1 --debug
✔ Subgraph name · jMyles/cypherbabies-sandbox1
✔ Directory to create the subgraph in · cypherbabies-sandbox1
———
✔ Cloning example subgraph
✔ Update subgraph name and commands in package.json
✔ Initialize subgraph repository
⠏ Install dependencies with yarn
```

**Comment by Jannis** [comment]
`yarn` must have a library so that instead of running it in a sub-shell you can execute a JS function that runs `yarn install` and takes a callback or similar for progress updates. I'll have to do some research on that.

I'm confident that what took so long was that some of the dependencies involve compiling native code for Node.js and that takes a while. Shouldn't be minutes but still, it would be good to have more feedback while `yarn` is running.

**Comment by azf20** [comment]
Closing, please re-open if still valid
