### ISSUE TITLE
graph deploy --help fails when subgraph.yaml is missing

### ISSUE THREAD

**Issue by aspiers** [graphprotocol/graph-tooling#754]
```
$ graph deploy --help 
ENOENT: no such file or directory, open '/path/to/subgraph/subgraph.yaml'
```

If I create that file, I get help as normal.

**Comment by saihaj** [comment]
Tested on latest release might have gotten fixed in #1055 migration https://github.com/graphprotocol/graph-tooling/releases/tag/release-1676989051474 but if you still see the issue let me know and we can revisit this. 

![CleanShot 2023-02-22 at 12 41 57](https://user-images.githubusercontent.com/44710980/220711171-26551444-99bd-4706-bad0-79ff543b5b66.png)
