### ISSUE TITLE
Codegen command generates setters for derived fields

### ISSUE THREAD

**Issue by georg-getz** [graphprotocol/graph-tooling#943]
The problem is that trying to call a setter of a derived field (some people do it when using [matchstick](https://github.com/LimeChain/matchstick)) crashes on deployment because derived fields are supposed to only be derived from other entities and not be set ever.

**Comment by azf20** [comment]
Thanks @georg-getz - agree that this is confusing
cc @evaporei

**Comment by KholdStare** [comment]
@evaporei @azf20 @dimitrovmaksim This just bit me - I was migrating away from manually setting a field to deriving it, and thought that building the graph would result in a compile error if a setter was being used anywhere. Turns out I missed removing a setter in one place, but only found out about it when the deployed graph had errors.

Just sharing another way this can affect users.
